import { guard, cleanSentences, tooLong, askClaude, fail } from "./_lib.js";
import { collect } from "./_db.js";

// Our own trained detector (see training/ and detector-space/). When DETECTOR_URL is set it is used:
//   DETECTOR_MODE=blend (default): our model + Claude + style statistics
//   DETECTOR_MODE=only:            our model + style statistics, no Claude at all
const envv = k => String(process.env[k] || "").trim();
async function ownModel(texts) {
  const url = envv("DETECTOR_URL"); if (!url) return null;
  try {
    const headers = { "content-type": "application/json" };
    if (envv("DETECTOR_KEY")) headers.authorization = "Bearer " + envv("DETECTOR_KEY");
    const ctl = new AbortController(); const t = setTimeout(() => ctl.abort(), 25000);
    const r = await fetch(url.replace(/\/+$/, "") + "/score", { method: "POST", headers, body: JSON.stringify({ texts }), signal: ctl.signal });
    clearTimeout(t);
    const d = await r.json().catch(() => ({}));
    if (!r.ok || !Array.isArray(d.scores) || d.scores.length !== texts.length) { console.error("own detector failed", r.status, d); return null; }
    return d.scores.map(x => clamp(Math.round(Number(x) * 100)));
  } catch (e) { console.error("own detector error", e && e.message); return null; }
}

// AI-writing estimate. Two independent signals are blended so one over-eager judgement
// can't push an honest essay to a high score:
//   1. a calibrated per-sentence reading by the model (temperature 0), and
//   2. measurable style statistics (sentence-length variety, stock AI phrases, personal voice).
// Formal or careful human writing is common in university work, so the default leans human.

const PHRASES = ["delve", "moreover", "furthermore", "additionally", "in conclusion", "it is important to note", "it's important to note",
  "plays a crucial role", "play a crucial role", "plays a pivotal role", "pivotal", "tapestry", "in today's", "rapidly evolving", "ever-evolving",
  "landscape", "foster", "notably", "underscore", "multifaceted", "realm", "showcase", "seamless", "robust", "leverage", "harness",
  "vibrant", "intricate", "testament", "comprehensive", "paramount", "embark", "holistic", "nuanced", "in summary", "a myriad of",
  "serves as", "navigate the", "navigating the", "it is worth noting", "in the realm of", "shed light on", "a deeper understanding",
  "ultimately,", "overall,", "in essence", "stands as", "game-changer", "unlock", "elevate"];

const clamp = (x, a = 0, b = 100) => Math.max(a, Math.min(b, x));
const wordsOf = s => s.match(/[A-Za-z’'-]+/g) || [];

function stats(sentences) {
  const text = sentences.map(s => s.text).join(" ");
  const words = wordsOf(text); const n = Math.max(1, words.length);
  const lens = sentences.map(s => wordsOf(s.text).length).filter(x => x > 0);
  const mean = lens.reduce((a, b) => a + b, 0) / Math.max(1, lens.length);
  const sd = Math.sqrt(lens.reduce((a, b) => a + (b - mean) ** 2, 0) / Math.max(1, lens.length));
  const cv = mean ? sd / mean : 0;
  const lower = text.toLowerCase();
  const phraseHits = PHRASES.reduce((c, p) => c + (lower.split(p).length - 1), 0);
  const phraseRate = phraseHits / n * 100;                      // stock phrases per 100 words
  const personal = (lower.match(/\b(i|i'm|i've|i'd|my|me|we|our)\b/g) || []).length + (lower.match(/\b\w+'(t|s|re|ve|ll|d|m)\b/g) || []).length;
  const personalRate = personal / n * 100;
  // Each sub-score: 0 = looks human, 100 = looks AI.
  const burst = lens.length < 4 ? 40 : clamp((0.55 - cv) / 0.30 * 100);   // even sentence lengths look AI
  const phr = clamp(phraseRate / 1.2 * 100);                               // ~1.2 stock phrases / 100 words = max
  const pers = clamp((2 - personalRate) / 2 * 50);                         // no personal voice is only a weak signal
  const score = 0.45 * burst + 0.40 * phr + 0.15 * pers;
  return { score, cv, phraseHits, phraseRate, personalRate, words: n };
}

export default async function handler(req, res) {
  const body = await guard(req, res); if (!body) return;
  const sentences = cleanSentences(body.sentences);
  if (!sentences.length) return res.status(400).json({ code: "empty" });
  if (tooLong(sentences)) return res.status(413).json({ code: "too_long" });

  const numbered = sentences.map(s => `[${s.i}] ${s.text}`).join("\n");
  const prompt = `You estimate whether each sentence of a university student's text was generated by an AI model (like ChatGPT) or written by the student. False accusations hurt students, so be strict about evidence and lean HUMAN when unsure.

Do NOT treat these as AI evidence on their own: formal or academic tone, correct grammar, good vocabulary, clear structure, topic sentences, citations, non-native English patterns, or simply being well written. Many careful human writers produce this.

Count as AI evidence only concrete markers: stock AI phrases ("delve", "it is important to note", "plays a crucial/pivotal role", "in today's rapidly evolving", "tapestry", "multifaceted", "navigate the landscape"), empty generic claims with no specifics, perfectly balanced lists of three repeated across sentences, hedging boilerplate, and the same sentence rhythm over and over.
Count as human evidence: specific details, examples, names, numbers, personal opinions or experiences, uneven rhythm, informal or idiosyncratic wording, small mistakes.

Calibration for each sentence's "likelihood":
- 0-20: ordinary human writing, including formal academic writing
- 20-40: polished and generic but a human could easily write it
- 40-70: two or more clear AI markers
- 70-100: obviously machine-like (several stock phrases, empty and formulaic)
A typical honest student essay should land mostly between 5 and 35.

Text, split into numbered sentences:
${numbered}

Reply with ONLY JSON:
{"score": <0-100 overall, following the same calibration>,
 "summary": "<2-3 plain sentences for the student: what (if anything) reads as AI, what reads as human, one revision tip>",
 "sentences": [{"i": <number>, "likelihood": <0-100>, "reason": "<under 16 words, name the concrete marker or say why it reads human>"}]}
Include every sentence number exactly once.`;

  try {
    const own = await ownModel(sentences.map(s => s.text));
    const onlyOwn = own && envv("DETECTOR_MODE").toLowerCase() === "only";
    const r = onlyOwn
      ? { score: null, summary: "", sentences: sentences.map((s, k) => ({ i: s.i, likelihood: own[k], reason: own[k] >= 50 ? "Our detector found AI-like patterns here." : "Reads like human writing to our detector." })) }
      : await askClaude(prompt, Math.min(8000, 600 + sentences.length * 60), { temperature: 0, model: process.env.AI_MODEL || undefined });
    if (own && !onlyOwn) {
      // Blend our model into Claude's per-sentence view (our model counts for 60%).
      const ownBy = new Map(sentences.map((s, k) => [s.i, own[k]]));
      r.sentences = (Array.isArray(r.sentences) ? r.sentences : []).map(x => ownBy.has(Number(x.i)) ? { ...x, likelihood: 0.6 * ownBy.get(Number(x.i)) + 0.4 * (Number(x.likelihood) || 0) } : x);
      r.score = null;
    }
    const st = stats(sentences);
    const list = (Array.isArray(r.sentences) ? r.sentences : []).map(x => ({ i: Number(x.i), likelihood: clamp(Math.round(Number(x.likelihood) || 0)), reason: String(x.reason || "").slice(0, 160) }));
    // Model's view: length-weighted mean of sentence likelihoods, blended with its overall number.
    const byI = new Map(list.map(x => [x.i, x]));
    let wsum = 0, lsum = 0;
    sentences.forEach(s => { const w = Math.max(1, wordsOf(s.text).length); const l = (byI.get(s.i) || { likelihood: 20 }).likelihood; wsum += w; lsum += w * l; });
    const modelMean = wsum ? lsum / wsum : 20;
    const modelScore = r.score == null ? modelMean : 0.5 * modelMean + 0.5 * clamp(Number(r.score) || modelMean);
    let score = 0.6 * modelScore + 0.4 * st.score;
    // Without measurable AI fingerprints (few stock phrases and varied sentences), don't report a high score.
    if (st.phraseRate < 0.4 && st.cv >= 0.42) score = Math.min(score, 35);
    else if (st.phraseRate < 0.6) score = Math.min(score, 55);
    // Very short texts can't be judged reliably: pull toward the middle-low range.
    if (st.words < 80) score = 0.6 * score + 0.4 * 25;
    score = Math.round(clamp(score));
    // Rescale sentence likelihoods so they agree with the overall result.
    const k = modelMean > 0 ? Math.min(1.2, score / modelMean) : 1;
    const sentencesOut = list.map(x => ({ ...x, likelihood: Math.round(clamp(x.likelihood * k)) }));
    const summary = String(r.summary || "") || (score >= 60 ? "Our detector found many AI-like sentences. Rewrite the highlighted ones in your own voice with specific details." : score >= 30 ? "Some sentences read as AI-like to our detector, but much of it reads human. Revise the highlighted sentences with your own examples." : "Most of this reads like human writing to our detector.");
    await collect(req, body, sentences.map(s => s.text).join(" "), { tool: "ai", modelScore: score });
    res.status(200).json({
      score, summary, sentences: sentencesOut, engine: own ? (onlyOwn ? "own" : "own+claude") : "claude",
      signals: [
        { label: `Sentence variety ${st.cv >= 0.45 ? "high" : st.cv >= 0.3 ? "medium" : "low"}`, level: st.cv >= 0.45 ? "good" : st.cv >= 0.3 ? "warn" : "bad" },
        { label: `${st.phraseHits} stock AI phrase${st.phraseHits === 1 ? "" : "s"}`, level: st.phraseRate < 0.4 ? "good" : st.phraseRate < 1 ? "warn" : "bad" },
      ],
    });
  } catch (e) { fail(res, e); }
}
